"""Seed legal knowledge base: clearly-marked demo content with real Act names, generic explanations."""
SEED_SOURCES = [
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Consumer Protection Act — Defective goods & deficiency in service", act="Consumer Protection Act", section="35", year=2019, jurisdiction="India", category="Consumer Law", content="A consumer complaint may be filed where goods are defective or services are deficient. Keep bills, warranty and written communication with the seller.", simple_explanation="If something you bought is faulty, you can complain with your bill and warranty as proof."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Bharatiya Nyaya Sanhita — Cheating", act="Bharatiya Nyaya Sanhita", section="318", year=2023, jurisdiction="India", category="Criminal Law", content="Cheating involves dishonestly inducing a person to deliver property or consent. Preserve messages, payment proof and report promptly.", simple_explanation="If someone tricked you into paying, save all proof and report it quickly."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Information Technology Act — Online fraud reporting", act="Information Technology Act", section="66D", year=2000, jurisdiction="India", category="Cyber Law", content="Cheating by personation using a computer resource is punishable. Report financial cyber fraud on helpline 1930 / cybercrime.gov.in immediately.", simple_explanation="For UPI/OTP fraud, call 1930 immediately and save transaction IDs."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Industrial Disputes / Wages — Unpaid salary", act="Payment of Wages Act", section="15", year=1936, jurisdiction="India", category="Employment Law", content="Employees should preserve offer letters, payslips and bank statements and raise written claims for unpaid wages.", simple_explanation="If salary is unpaid, keep your offer letter and payslips and write to your employer."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Rent & tenancy — Security deposit", act="Model Tenancy Act (reference)", section="General", year=2021, jurisdiction="India", category="Property Law", content="Security deposit terms are governed by the rental agreement and applicable state rent law. Review the agreement and send a written refund request.", simple_explanation="Deposit refunds depend on your agreement and state law; always ask in writing."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="RTI — Seeking information from public authorities", act="RTI Act", section="6", year=2005, jurisdiction="India", category="Civil Law", content="A citizen may request information from a public authority with a simple application and prescribed fee.", simple_explanation="You can ask government offices for information with a simple RTI letter."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Negotiable Instruments — Cheque bounce", act="Negotiable Instruments Act", section="138", year=1881, jurisdiction="India", category="Banking & Finance", content="Cheque dishonour requires a written demand notice within the statutory timeline before further steps.", simple_explanation="For a bounced cheque, a written notice within time is the first step."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="POSH — Workplace harassment", act="POSH Act", section="9", year=2013, jurisdiction="India", category="Women & Child Rights", content="An aggrieved employee may complain to the Internal Committee in writing; escalation to human help is advised.", simple_explanation="Workplace harassment complaints go to the Internal Committee in writing."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Motor Vehicles — Accident claims", act="Motor Vehicles Act", section="166", year=1988, jurisdiction="India", category="Civil Law", content="Compensation claims for motor accidents require FIR, medical and vehicle records.", simple_explanation="Keep FIR and medical papers for accident claims."),
    dict(source_name="India Code (demo excerpt)", source_url="https://www.indiacode.nic.in", title="Constitution — Right to equality & life", act="Constitution of India", section="Art. 14, 21", year=1950, jurisdiction="India", category="Civil Law", content="Foundational rights overview for general awareness; specific remedies depend on facts.", simple_explanation="Basic rights overview; details depend on your situation."),
]
