// Pre-loaded verified lawyer profiles (demo). Shown if the API is unreachable;
// the live directory (GET /api/lawyers) remains the source of truth when online.
export const DEMO_LAWYERS = [
  { id: "demo-1", slug: "adv-rohan-desai-mh-22231-2015", full_name: "Adv. Rohan Desai", email: "rohan.desai@demo.in", city: "Pune", state: "Maharashtra", experience_years: 11, practice_areas: ["Employment Law", "Labour Law"], languages: ["en", "mr", "hi"], bio: "Adv. Rohan Desai practices Employment and Labour Law with 11 years of experience, helping salaried employees with unpaid dues, termination and workplace claims.", courts: ["District Court", "High Court"], availability: "Available", verified: true, rating: 4.8 },
  { id: "demo-2", slug: "adv-priya-nair-kl-98765-2016", full_name: "Adv. Priya Nair", email: "priya.nair@demo.in", city: "Kochi", state: "Kerala", experience_years: 9, practice_areas: ["Family Law", "Women & Child Rights"], languages: ["en", "hi"], bio: "Adv. Priya Nair practices Family Law and Women & Child Rights with 9 years of experience, guiding clients through divorce, custody and maintenance matters.", courts: ["Family Court", "High Court"], availability: "Available", verified: true, rating: 4.9 },
  { id: "demo-3", slug: "adv-vikram-singh-dl-33445-2012", full_name: "Adv. Vikram Singh", email: "vikram.singh@demo.in", city: "New Delhi", state: "Delhi", experience_years: 14, practice_areas: ["Criminal Law", "Cyber Law"], languages: ["en", "hi"], bio: "Adv. Vikram Singh practices Criminal and Cyber Law with 14 years of experience, assisting with FIRs, bail, fraud and online scam cases.", courts: ["District Court", "High Court"], availability: "Available", verified: true, rating: 4.7 },
  { id: "demo-4", slug: "adv-kavya-iyer-tn-11223-2017", full_name: "Adv. Kavya Iyer", email: "kavya.iyer@demo.in", city: "Chennai", state: "Tamil Nadu", experience_years: 9, practice_areas: ["Consumer Law", "Civil Law"], languages: ["en", "ta"], bio: "Adv. Kavya Iyer practices Consumer and Civil Law with 9 years of experience, helping buyers with refunds, defective products and seller disputes.", courts: ["Consumer Commission", "District Court"], availability: "Available", verified: true, rating: 4.8 },
  { id: "demo-5", slug: "adv-arjun-reddy-ap-45678-2019", full_name: "Adv. Arjun Reddy", email: "arjun.reddy@demo.in", city: "Hyderabad", state: "Telangana", experience_years: 6, practice_areas: ["Corporate Law", "Startup & Business Law"], languages: ["en", "te"], bio: "Adv. Arjun Reddy practices Corporate and Startup Law with 6 years of experience, advising founders on incorporation, contracts and compliance.", courts: ["High Court", "NCLT"], availability: "Available", verified: true, rating: 4.6 },
  { id: "demo-6", slug: "adv-sneha-kulkarni-mh-77889-2020", full_name: "Adv. Sneha Kulkarni", email: "sneha.k@demo.in", city: "Nagpur", state: "Maharashtra", experience_years: 5, practice_areas: ["Tax Law", "Banking & Finance"], languages: ["en", "mr"], bio: "Adv. Sneha Kulkarni practices Tax and Banking Law with 5 years of experience, assisting with GST notices, loans and cheque-bounce matters.", courts: ["District Court", "DRT"], availability: "Available", verified: true, rating: 4.7 },
  { id: "demo-7", slug: "adv-farhan-qureshi-gj-99001-2014", full_name: "Adv. Farhan Qureshi", email: "farhan.q@demo.in", city: "Ahmedabad", state: "Gujarat", experience_years: 12, practice_areas: ["Intellectual Property", "Corporate Law"], languages: ["en", "gu", "hi"], bio: "Adv. Farhan Qureshi practices Intellectual Property and Corporate Law with 12 years of experience, handling trademarks, copyrights and business contracts.", courts: ["District Court", "High Court"], availability: "Available", verified: true, rating: 4.8 },
  { id: "demo-8", slug: "adv-divya-rao-ka-55667-2018", full_name: "Adv. Divya Rao", email: "divya.rao@demo.in", city: "Bengaluru", state: "Karnataka", experience_years: 7, practice_areas: ["Cyber Law", "Consumer Law"], languages: ["en", "kn"], bio: "Adv. Divya Rao practices Cyber and Consumer Law with 7 years of experience, helping victims of UPI fraud, phishing and online shopping disputes.", courts: ["District Court", "Consumer Commission"], availability: "Available", verified: true, rating: 4.9 },
];
